### ISSUE TITLE
Windows PC - Memory node error

### ISSUE THREAD

**Issue by thebaldgeek** [TheOVIAproject/node-red-contrib-ovia-os#1]
Looking to use these nodes on a Windows 7 Laptop running Node-RED.

The 'Drives' node crashes Node-RED (Will try and get the console error dump soon).

The 'Memory' node produces the following error; "Error: ENOENT: no such file or directory, open 'C:\proc\meminfo'"

The 'NetworkIntf' processes no output.

OS, Uptime and CPU's nodes work as expected. 

Node-RED version v0.16.1
Node.js version v6.9.4

Windows 7 Pro.
Service Pack 1.
i7-2620.
8gB RAM.
64-Bit.

**Comment by TuxSeb** [comment]
@thebaldgeek 
Hello, This currently not work because the code only work on Linux based OS, this node is made for our project, but you can try the original node https://github.com/Argonne-National-Laboratory/node-red-contrib-os , this one should work with windows.

Thanks you !

**Comment by thebaldgeek** [comment]
Thanks.
Perhaps a slight tweak of the description on the page would be helpful, it sounds like the nodes will work with windows a few times on the page.

I uninstalled those nodes and installed the nodes you suggested..... They all work Ok except for the 'Disk' node. It still crashes Node-RED with the error 'The command df can not be found'.
Looks like even that different set of Nodes are expected to run on Linux.
Still the others work Ok, so thanks for the tip and appreciate the nodes.
